package com.accenture.kafka.client.producter;

import java.util.Random;

/**
 * Created by THINK on 2016/11/22.
 */
public class RandomStrings {
    final static Random random = new Random();

    public static String get() {
        return source[random.nextInt(source.length)];
    }

    public static final String[] source = new String[]{
            "The pact is sealed! ",
            "You called? ",
            "My patience has ended! ",
            "I am the Darkness! ",
            "My vengence is yours! ",
            "Let battle be joined! ",
            "As you order! ",
            "Hiyah! ",
            "At last! ",
            "For the Lich King!",
            "Has hell frozen over yet? ",
            "I am the one horseman of the Apocalypse. ",
            "I hate people, but I love gatherings! ",
            "I''m a Death Night Rider! Muh ha ha ha ",
            "Blueca!**- Don''t touch me... I''m evil! ",

            "The night beckons! ",
            "Greetings! ",
            "What, mortal? ",
            "What is it now? ",
            "I must hunt soon! ",
            "That was my plan! ",
            "Agreed! ",
            "Very well. ",
            "You thought of that? ",
            "If I have wings, why am I always walking? ",
            "Yes? Arrgghh! For the last time, I''m a Dread Lord, not a Drug Lord! ",
            "This is not a dress, it''s the standard Dread Lord uniform!",
            "Dress to kill! Blah! ",
            "Yes? Darkness, hey, what''s up? The Demon Hunter left you a mess age? No, I don''t have his number. ",
            "And then, after I overthrow this fool... Oh! Hello! I didn''t know you were there. ",
            "The sleeper awakes! ",
            "Proceed! ",
            "Make your choice!",
            "You rang? ",
            "I await. ",
            "Rise! ",
            "By Narube!** ",
            "What''s done is done! ",
            "The time is now! ",
            "Yes, Master! ",
            "What a tangled web we weave!",
            "Spider sense tingling- Last week my top half was on the Discovery channel. ",
            "And my bottom half was on Animal Planet. ",
            "My ass always gets bloated during my spin cycle! ",
            "I like chicks that are into bandage! ",
            "I''m stuck on bandages, ''cause bandages are stuck on me!* ",

            "The ancient evil survives! ",
            "I am sworn to Nazul! ",
            "Thy bidding? ",
            "Direct me! ",
            "Yours to command! ",
            "Cllleeaarrr! ",
            "Nazul protect them!Ner ''zhul",
            "Freeze! ",
            "So be it! ",
            "By your words! ",
            "It it destined! ",
            "Dead man walking! ",
            "Chilling! ",
            "Could you chew that up for me? ",
            "I''m so poor, I don''t even have calcium deposits! ",
            "I am the Ghost of Warcraft past.",
            "I hear that banshee''s a real screamer! ",
            "You should see the skeletons in my closet! ",
            "all the ladies dig rigor mortis. ",
            "You are the Weakest Link, goodbye! ",

            "Me eat dead people! ",
            "Me scary! ",
            "Me eat brains! ",
            "No guts, no glory! ",
            "Us hear and obey!* ",
            "What we do?* ",
            "Egghhhh?* ",
            "We done waiting!",
            "Hmmmm. ",
            "Us go!* ",
            "Egghhhh?* ",
            "Random terror!* ",


            "We come in peace... es! ",
            "All for one! ",
            "Kill! ",

            "Tear meat! ",
            "Rip! ",
            "The shadows beckon! ",
            "The dead shall serve! ",
            "The restless dead await! ",
            "What does the shadow will? ",
            "This better be good! ",
            "Awaken! ",
            "Intriguing! ",
            "For the Lich King!",
            "Let Darkness guide me! ",
            "As the shadow wills! ",
            "Every man lives, not every man truely dies! ",
            "I love the dead... frequently! ",
            "They''ll all be mine in the end! ",
            "Die! ",
            "Tremble before the scourge! ",
            "None shall survive! ",
            "Let my cries chill the living! ",
            "You call to me? ",
            "You brought me back? ",
            "Why have I been summoned? ",
            "What must I do? ",
            "High!* high",
            "If it pleases you. ",
            "Yes. ",
            "If I must. ",
            "I must obey. ",
            "If that is your wish. ",
            "Let this torment end! ",
            "How long must I suffer? ",
            "U. N. D. E. A. D. Find out what it means to me! U N D E A D，",
            "There is no banshee, only Zul!** ",
            "I hate you, I hate you... call me! ",
            "My death awaits! ",
            "Die! ",
            "Feel my pain! ",
            "Your soul shall burn! ",
            "The damned return! ",
            "I shall be your eyes! ",
            "My sight is yours! ",
            "What needs revealing? ",
            "Let''s see. ",
            "I''ll look into it.",
            "All shall be revealed. ",
            "I go unseen! ",
            "I''m but a shadow of my former self.",
            "What I do in death echoes in eternity! ",
            "Death is its own reward! ",
            "I''m having a mid-death crisis! ",
            "I ain''t got no body! ",
            "I''m invisible, gaseous, and deadly! ",
            "Glory to the scourge! ",
            "More souls for the Master! ",
            "Die! ",
            "Let screams fill the air! ",
            "Feel my rath! ",
            "For the Master! ",
            "The sleeper awakes! ",
            "Proceed! ",
            "Make your choice!",
            "You rang? ",
            "I await. ",
            "Rise! ",
            "By Narube!** ",
            "What’s done is done! ",
            "The time is now! ",
            "Yes, Master! ",
            "Whata tangled web we weave!",
            "Spider sense tingling.",
            "Last week my top half was on the Discovery channel. ",
            "And my bottom half was on Animal Planet. ",
            "My ass always gets bloated during my spin cycle! ",
            "I like chicks that are into bandage! ",
            "I’m stuck on bandages, ’cause bandages are stuck on me!* ",
            "Fall before the scourge! ",
            "For the Spider Kingdom! ",
            "Be drained of life! ",
            "You may feel a sting. ",
            "The future is ours! ",
            "My eyes are open. ",
            "Seeing is believing! ",
            "Do you need my counsel? ",
            "Destiny awaits. ",
            "It is certain. ",
            "Of course. ",
            "I see. ",
            "Watch out!",
            "I see dead people. ",
            "Touch you tongue to mine! ",
            "Concentrate and ask again. ",
            "Outlook not so good. ",
            "Reply hazy. Try again! ",
            "Spirits of Earth and Storm, strike! ",
            "Strike! ",
            "Look out! ",
            "Attack! ",
    };
}
